### ISSUE TITLE
Support for humidity sensor

### ISSUE THREAD

**Issue by Tscherno** [aglehmann/pyEcovent#2]
Hi,

first: Thank you for the project. Works perfect on a Blauberg A50-W. Just a feature request: It should be possible to read the current humidity. Would be nice to have that too.

PS: If you ever start using NodeRed: a module for that would be even more awesome ;)

**Comment by aglehmann** [comment]
Hi,
Sorry for not getting back to you sooner. This project is my way of learning HA and python, so things are developing slowly. I'll have a look at implementing humidity reading.

I'm not using NodeRed my self but shouldn't the custom component I created work with NodeRed?
[https://github.com/aglehmann/home_assistant_ecovent]

**Comment by aglehmann** [comment]
Hi,
Humidity support is now available.
