### ISSUE TITLE
How to I get the ip adress of the fan? #4

### ISSUE THREAD

**Issue by cmartin81** [aglehmann/pyEcovent#5]
Where can i find the ip adress of the fan? I have a list of ips inside my network, but it is hard to know which one is connected to the fan

**Comment by aglehmann** [comment]
The easiest is probably to download some sort of IP scanner on your computer or phone, to scan your network. Then you need to look at the MAC addresses to figure out whats what. Some Apps for phones does this automatically, the MAC address for my fans starts with "A0:20:A6" which resolves to a vendor called "Espressif Inc.".
